[project]
name="learning_common_lib"
version="0.0.1"
requires-python = ">=3.10,<3.11"
dependencies = [
    "fastapi>=0.121.3",
]
[build-system]
requires = ["hatchling>=1.17.1"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src/learning_common_lib"]
